//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvChStreetsInformation.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Streets
    {
        public Streets()
        {
            this.Categories = new HashSet<Categories>();
        }
    
        public int Id { get; set; }
        public string StreetName { get; set; }
        public string StreetDesc { get; set; }
        public System.Data.Entity.Spatial.DbGeography point { get; set; }
    
        public virtual ICollection<Categories> Categories { get; set; }
    }
}
